from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]/'public'; HTML=(ROOT/'index.html').read_text().replace('<script src="/app.js" defer></script>',''); JS=(ROOT/'app.js').read_text()
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True, executable_path='/usr/bin/chromium', args=['--no-sandbox']); page=browser.new_page(viewport={'width':1440,'height':1000}); errors=[]; page.on('pageerror',lambda e:errors.append(str(e))); page.set_content(HTML)
    page.evaluate(r'''window.__state={notifications:[{id:2,type:'application',title:'Candidature',content:'Mise à jour',is_read:1,created_at:'2026-08-09T09:00:00Z'}],messages:[{id:30,sender_id:2,content:'Reçu',created_at:'2026-08-09T08:00:00Z'},{id:31,sender_id:1,content:'Envoyé',created_at:'2026-08-09T08:05:00Z'}],apps:[{id:10,status:'submitted',job_id:5,title:'Comptable',company_name:'Entreprise',location:'Abidjan',employment_type:'CDI',salary:'300000',created_at:'2026-08-09T08:00:00Z'}],calls:[]};window.fetch=async function(url,opts={}){const raw=String(url),p=raw.replace(/([?&])_fresh=\d+(&|$)/,'$1').replace(/[?&]$/,''),M=(opts.method||'GET').toUpperCase();window.__state.calls.push([M,p]);const R=(o,s=200)=>({ok:s>=200&&s<300,status:s,json:async()=>o});if(p==='/api/session')return R({user:{id:1,email:'candidate@test.ci',role:'candidate'},subscription:{plan:'standard',effective_status:'active',expires_at:'2026-09-01'}});if(p==='/api/public-stats')return R({jobs:1,companies:1,candidates:1,movement:{}});if(p==='/api/profile')return R({profile:{first_name:'Awa',last_name:'Kouassi'}});if(p==='/api/notifications')return R({notifications:window.__state.notifications});if(/^\/api\/notifications\/\d+$/.test(p)&&M==='DELETE'){window.__state.notifications=[];return R({ok:true})}if(p==='/api/candidate/applications')return R({applications:window.__state.apps});if(/^\/api\/candidate\/applications\/\d+\/action$/.test(p)){const a=window.__state.apps[0],act=JSON.parse(opts.body).action;a.status=act==='cancel'?'cancelled':act==='reactivate'?'submitted':'withdrawn';return R({ok:true,status:a.status})}if(p==='/api/conversations')return R({conversations:[{id:40,other_user_id:2,other_name:'Entreprise',other_role:'recruiter',last_message:'Bonjour'}]});if(p.startsWith('/api/messages?'))return R({messages:window.__state.messages});if(/^\/api\/messages\/\d+$/.test(p)&&M==='DELETE'){window.__state.messages=window.__state.messages.filter(x=>x.id!==+p.split('/').pop());return R({ok:true})}if(/^\/api\/conversations\/\d+$/.test(p)&&M==='DELETE')return R({ok:true});if(p==='/api/account/delete-request')return R({ok:true,request_id:99},201);if(p==='/api/change-password'||p==='/api/account/logout-all')return R({ok:true});return R({});}'''); page.add_script_tag(content=JS); page.wait_for_timeout(200)
    page.evaluate("navigateView('notifications')"); page.wait_for_timeout(60); page.locator('.notification-delete[data-id="2"]').click(); page.wait_for_timeout(20); assert 'Supprimer cette notification ?' in page.locator('#modalBody').inner_text(); page.locator('#professionalConfirmOk').click(); page.wait_for_timeout(80); assert page.locator('.notification-click[data-id="2"]').count()==0
    page.evaluate("navigateView('myapplications')"); page.wait_for_timeout(60); page.locator('.myapp-cancel[data-id="10"]').click(); assert 'Annuler cette candidature ?' in page.locator('#modalBody').inner_text(); page.locator('#professionalConfirmOk').click(); page.wait_for_timeout(80); assert page.locator('.myapp-reactivate[data-id="10"]').count()==1
    page.evaluate("navigateView('messages')"); page.wait_for_timeout(60); page.locator('.open-conv').click(); page.wait_for_timeout(40); assert page.locator('.message-delete-client').count()==2; page.locator('.message-delete-client[data-id="31"]').click(); assert 'Ce message sera masqué uniquement' in page.locator('#modalBody').inner_text(); page.locator('#professionalConfirmOk').click(); page.wait_for_timeout(80)
    page.locator('#closeModal').click(); page.evaluate("navigateView('messages')"); page.wait_for_timeout(60); page.locator('.conversation-delete-client').click(); assert 'Supprimer cette conversation ?' in page.locator('#modalBody').inner_text(); page.locator('#professionalConfirmCancel').click()
    page.evaluate("navigateView('settings')"); page.wait_for_timeout(60); page.locator('#deleteMyAccount').click(); assert 'Demander la suppression définitive ?' in page.locator('#modalBody').inner_text(); page.locator('#professionalConfirmOk').click(); page.wait_for_timeout(60); assert any('/api/account/delete-request' in c[1] for c in page.evaluate('window.__state.calls'))
    footer=page.locator('.premium-footer').inner_text(); assert 'GLOBAL EMPLOI' in footer and 'MEGA SERVICES SARL U' in footer and 'CI-BKE-2020-B-1150' in footer and '© 2026 GLOBAL EMPLOI - Tous droits réservés' in footer
    assert not errors,errors; print('V37_FRONTEND_OK'); browser.close()
